import 'package:flutter/foundation.dart' show SynchronousFuture;
import 'package:flutter/material.dart';

class AppLocalizations {
  final Locale locale;

  AppLocalizations(this.locale);

  static AppLocalizations of(BuildContext context) {
    return Localizations.of<AppLocalizations>(context, AppLocalizations)!;
  }

  static final Map<String, Map<String, String>> _localizedValues = {
    'en': {
      'login_title': 'Login',
      'login_message': 'Log in with your credentials.',
      'email': 'Email',
      'password': 'Password',
      'forgot_password': 'Forgot password?',
      'login_button': 'Log In',
      'signup_button': 'Sign Up (Customers)',
      'reset_password_message': 'Enter your email to reset your password.',
      'reset_password_button': 'Reset Password',
      'back_to_login': 'Back to Login',
      'signup_message': 'Sign up here for the customer area.',
      'registration_button': 'Register',
      'login_user_title': 'Log in with your credentials',
      'login_guest_title': 'Continue as Guest',
      'login_user_icon': 'Login with credentials icon',
      'login_guest_icon': 'Continue as guest icon',
      'logo_alt_text': 'Company Logo',
      'enter_email_label': 'Enter your Email',
      'confirm_button': 'Confirm and Continue',
      'email_verification_title': 'Verify Email',
      'verification_message': 'We have sent an email to {email}. Please verify your email address.',
      'change_email': 'Change Email',
      'email_verified_checkbox': 'I have verified my email',
      'email_not_received_message': 'Didn\'t receive the email? Check your spam folder or request the email again.',
      'resend_email': 'Resend Email',
      'resend_email_cooldown': 'Resend Email ({seconds}s)',
      'confirm_button_label': 'Confirm',
      'email_invalid': 'Please enter a valid email address.',
      'email_already_verified': 'Email is already verified.',
      'email_not_verified': 'Email not verified. Please check your email.',
      'email_sent': 'Email has been sent again.',
      'aufzeichnen_screen_title': 'Record Tour',
      'aufzeichnen_tab_title': 'Record',
      'scorings_tab_title': 'Scorings',
      'touren_tab_title': 'Tours',
      'aufzeichnen_tab_distance_title': 'Distance in km',
      'aufzeichnen_tab_average_speed_title': 'Average Speed in km/h',
      'aufzeichnen_tab_speed_title': 'Speed in km/h',
      'aufzeichnen_tab_time_title': 'Time in h:m:s',
      'scorings_tab_activity_title': 'Activity',
      'scorings_tab_activity_subtitle': 'Your recorded tours',
      'scorings_tab_today': 'Today',
      'scorings_tab_this_week': 'This week',
      'scorings_tab_this_month': 'This month',
      'scorings_tab_this_year': 'This year',
      'scorings_tab_total_distance_title': 'Total Distance',
      'scorings_tab_total_distance_subtitle': '0.00 km',
      'scorings_tab_total_duration_title': 'Total Duration',
      'scorings_tab_total_duration_subtitle': '0 h 0 m 0 s',
      'scorings_tab_average_title': 'Average',
      'scorings_tab_average_subtitle': '0.00 km/h',
      'scorings_tab_longest_tour_title': 'Longest Tour',
      'scorings_tab_longest_tour_subtitle': '0.00 km',
      'add_bike_card_title': 'Add Bike',
      'add_bike_card_message': 'Use the app with all features.',
      'content_view_title': 'Guide',
      'more_posts': 'More Posts',
      'info_card_title': 'Title',
      'info_card_description': 'Description',
      'service_card_1_title': 'Specialized Dealers and Workshops',
      'service_card_1_subtitle': 'Find workshops and dealers near you.',
      'service_card_2_title': 'Pick-up Service',
      'service_card_2_subtitle': 'Easily request pick-up service\nand have your bike towed in an emergency.',
      'info_card_1_title': 'Bike Pass',
      'info_card_1_description': 'Collect key data about your bike in the app.',
      'info_card_2_title': 'Find Location',
      'info_card_2_description': 'Find workshops, accommodations, and many other locations near you.',
      'mehr_screen_title': 'More',
      'advice_card': 'Advice',
      'videos_card': 'Videos',
      'insurance_card': 'Insure Another Bike',
      'notification_settings_card': 'Notification Settings',
      'feedback_card': 'Feedback',
      'recommend_app_card': 'Recommend App',
      'contact_app_team_card': 'Contact App Team',
      'about_app_card': 'About the App',
      'legal_card': 'Legal',
      'share_app_message': 'Check out this demo app: Linexo-demo',
      'feedback_title': 'Send Feedback',
      'feedback_hint': 'Enter your feedback',
      'submit_button': 'Submit',
      'error_user_not_logged_in': 'Error: User not logged in',
      'ok_button': 'OK',
      'about_app_title': 'About the App',
      'about_app_description': 'Developer: Sinan Qarhiely\nEmail: sinan.qarhiely@gmail.com',
      'legal_title': 'Legal and Privacy',
      'legal_description': 'This app is committed to protecting your personal data according to applicable privacy laws. All collected information is used solely to enhance user experience and is not shared with third parties without your explicit consent. Your data is securely stored and treated confidentially. If you have any questions or concerns regarding your data or our privacy policies, please contact us.',
      "greeting_guest": "Hello Guest",
      "greeting_user": "Hello, {firstName} {lastName}",
      "greeting_default": "Hello User",
      "confirm_logout": "Are you sure you want to log out?",
      "confirm_delete_account": "Are you sure you want to delete your account?",
      "profile_title": "Profile",
      "my_bikes": "My Bikes",
      "personal_data": "Personal Data",
      "my_contracts": "My Contracts",
      "my_favorites": "My Favorites",
      "logout": "Logout",
      "delete_account": "Delete Account",
      "delete_account_text": "Here you can delete your account.",
      "dark_mode": "Dark Mode",
      "error_fetching_role": "Error fetching user role",
      "cancel": "Cancel",
      "confirm": "Confirm",
      "loading_text": "Loading...",
      'guest_page_title': 'Guest Page',
      'guest_message': 'You are a guest and cannot use this functionality.',
      'guest_suggestion': 'Create a user account to use this functionality.',
      'articles_screen_title': 'Guide',
      'no_articles_available': 'No articles available',
      'all': 'All',
      'user_page_title': 'User Page',
      'user_message': 'You are a user and you are allowed to use this functionality.',
      'content_card_title': 'Your Content Title',
      "form_submission_success": "Form submitted successfully!",
      "error_generic": "Error: {error}",
      "select_previous_image": "Please select the previous image first.",
      "permission_denied": "Permission denied!",
      "permission_permanently_denied": "Permission permanently denied. Please enable it in settings.",
      "select_image_source": "Select Image Source",
      "camera": "Camera",
      'image_picker_title': 'Pick an Image',
      "gallery": "Gallery",
      "select_topic": "Select Topic",
      "select_topic_error": "Please select a topic",
      "first_name": "First Name",
      "first_name_error": "Please enter your first name.",
      "last_name": "Last Name",
      "last_name_error": "Please enter your last name.",
      "phone": "Phone",
      "message_hint": "Brief message",
      "message_error": "Please enter a message",
      "terms_agreement": "By entering my data and pressing the button 'Send Message', I consent to the use of the provided data to respond to my contact request.",
      "send_message": "Send Message",
      "contact_form": "Contact Form",
      "support": "Support",
      "call_phone_number": "Call {phoneNumber}",
      "call": "Call",
      "frequently_asked_questions": "Frequently Asked Questions",
      "live_chat": "Live Chat",
      "live_chat_hours": "Mon-Fri from 8:00 AM to 7:00 PM",
      "customer_service": "Customer Service",
      "customer_service_hours": "Mon-Fri from 8:00 AM to 8:00 PM\nSat from 8:00 AM to 4:00 PM"

    },
    'de': {
      'login_title': 'Login',
      'login_message': 'Melde dich hier mit den Zugangsdaten aus dem Kundenportal an.',
      'email': 'E-Mail',
      'password': 'Passwort',
      'forgot_password': 'Passwort vergessen?',
      'login_button': 'Einloggen',
      'signup_button': 'Registrieren (Kunden)',
      'reset_password_message': 'Gib deine E-Mail-Adresse ein, um dein Passwort zurückzusetzen.',
      'reset_password_button': 'Passwort zurücksetzen',
      'back_to_login': 'Zurück zum Login',
      'signup_message': 'Registriere dich hier für den Kundenbereich.',
      'registration_button': 'Registrieren',
      'login_user_title': 'Mit Kundendaten anmelden',
      'login_guest_title': 'Weiter als Gast',
      'login_user_icon': 'Icon für Anmeldung mit Zugangsdaten',
      'login_guest_icon': 'Icon für Weiter als Gast',
      'logo_alt_text': 'Firmenlogo',
      'enter_email_label': 'Gib deine E-Mail-Adresse ein',
      'confirm_button': 'Bestätigen und Fortfahren',
      'email_verification_title': 'E-Mail bestätigen',
      'verification_message': 'Wir haben dir eine E-Mail an {email} geschickt. Bitte bestätige deine E-Mail-Adresse.',
      'change_email': 'E-Mail ändern',
      'email_verified_checkbox': 'Ich habe meine E-Mail verifiziert',
      'email_not_received_message': 'Hast du die E-Mail nicht erhalten? Überprüfe deinen Spam-Ordner oder lass dir die E-Mail erneut zuschicken.',
      'resend_email': 'E-Mail erneut schicken',
      'resend_email_cooldown': 'E-Mail erneut schicken ({seconds}s)',
      'confirm_button_label': 'Bestätigen',
      'email_invalid': 'Bitte gib eine gültige E-Mail-Adresse ein.',
      'email_already_verified': 'E-Mail ist bereits verifiziert.',
      'email_not_verified': 'E-Mail nicht verifiziert. Bitte überprüfe deine E-Mail.',
      'email_sent': 'E-Mail wurde erneut gesendet.',
      'aufzeichnen_screen_title': 'Tour aufzeichnen',
      'aufzeichnen_tab_title': 'Aufzeichnen',
      'scorings_tab_title': 'Scorings',
      'touren_tab_title': 'Touren',
      'aufzeichnen_tab_distance_title': 'Distanz in km',
      'aufzeichnen_tab_average_speed_title': 'Durchschnitt in km/h',
      'aufzeichnen_tab_speed_title': 'Geschwindigkeit in km/h',
      'aufzeichnen_tab_time_title': 'Zeit in h:m:s',
      'scorings_tab_activity_title': 'Aktivität',
      'scorings_tab_activity_subtitle': 'Deine aufgezeichneten Touren',
      'scorings_tab_today': 'Heute',
      'scorings_tab_this_week': 'diese Woche',
      'scorings_tab_this_month': 'diesen Monat',
      'scorings_tab_this_year': 'dieses Jahr',
      'scorings_tab_total_distance_title': 'Gesamtstrecke',
      'scorings_tab_total_distance_subtitle': '0,00 km',
      'scorings_tab_total_duration_title': 'Gesamtdauer',
      'scorings_tab_total_duration_subtitle': '0 h 0 m 0 s',
      'scorings_tab_average_title': 'Durchschnitt',
      'scorings_tab_average_subtitle': '0,00 km/h',
      'scorings_tab_longest_tour_title': 'Längste Tour',
      'scorings_tab_longest_tour_subtitle': '0,00 km',
      'add_bike_card_title': 'Bike hinzufügen',
      'add_bike_card_message': 'Die App mit allen Funktionen nutzen.',
      'content_view_title': 'Ratgeber',
      'more_posts': 'Mehr Beiträge',
      'info_card_title': 'Titel',
      'info_card_description': 'Beschreibung',
      'service_card_1_title': 'Fachhändler und Werkstätten',
      'service_card_1_subtitle': 'Finde Werkstätten und Fachhändler in deiner Nähe.',
      'service_card_2_title': 'Pick-up-Service',
      'service_card_2_subtitle': 'Einfach Pick-up-Service anfordern\nund im Notfall abschleppen lassen.',
      'info_card_1_title': 'Fahrradpass',
      'info_card_1_description': 'Sammle die wichtigsten Daten rund um dein Bike in der App.',
      'info_card_2_title': 'Standort finden',
      'info_card_2_description': 'Finde Werkstätten, Unterkünfte und viele andere Standorte in deiner Nähe.',
      'mehr_screen_title': 'Mehr',
      'advice_card': 'Ratgeber',
      'videos_card': 'Videos',
      'insurance_card': 'Weiteres Fahrrad versichern',
      'notification_settings_card': 'Mitteilungseinstellungen',
      'feedback_card': 'Feedback',
      'recommend_app_card': 'App empfehlen',
      'contact_app_team_card': 'Kontakt zum App-Team',
      'about_app_card': 'Über die App',
      'legal_card': 'Rechtliches',
      'share_app_message': 'Schau dir diese Demo-App an: Linexo-demo',
      'feedback_title': 'Feedback senden',
      'feedback_hint': 'Geben Sie Ihr Feedback ein',
      'submit_button': 'Absenden',
      'error_user_not_logged_in': 'Fehler: Benutzer nicht eingeloggt',
      'ok_button': 'OK',
      'about_app_title': 'Über die App',
      'about_app_description': 'Entwickler: Sinan Qarhiely\nE-Mail: sinan.qarhiely@gmail.com',
      'legal_title': 'Rechtliches und Datenschutz',
      'legal_description': 'Diese App verpflichtet sich, Ihre persönlichen Daten gemäß den geltenden Datenschutzgesetzen zu schützen. Alle erfassten Informationen werden ausschließlich zur Verbesserung der Benutzererfahrung verwendet und nicht ohne Ihre ausdrückliche Zustimmung an Dritte weitergegeben. Ihre Daten werden sicher gespeichert und vertraulich behandelt. Bei Fragen oder Anliegen bezüglich Ihrer Daten oder unserer Datenschutzrichtlinien stehen wir Ihnen gerne zur Verfügung.',
      "greeting_guest": "Hallo Gästin oder Gast",
      "greeting_user": "Hallo, {firstName} {lastName}",
      "greeting_default": "Hallo, User",
      "confirm_logout": "Bist du sicher, dass du dich abmelden möchtest?",
      "confirm_delete_account": "Bist du sicher, dass du deinen Account löschen möchtest?",
      "profile_title": "Profil",
      "my_bikes": "Meine Bikes",
      "personal_data": "Persönliche Daten",
      "my_contracts": "Meine Verträge",
      "my_favorites": "Meine Favoriten",
      "logout": "Abmelden",
      "delete_account": "Account löschen",
      "delete_account_text": "Hier kannst du deinen Account löschen.",
      "dark_mode": "Dunkelmodus",
      "error_fetching_role": "Fehler beim Abrufen der Benutzerrolle",
      "cancel": "Abbrechen",
      "confirm": "Bestätigen",
      "loading_text": "Wird geladen...",
      'guest_page_title': 'Gastseite',
      'guest_message': 'Du bist ein Gast und kannst diese Funktionalität nicht nutzen.',
      'guest_suggestion': 'Erstelle ein Benutzerkonto, um diese Funktionalität nutzen zu können.',
      'articles_screen_title': 'Ratgeber',
      'no_articles_available': 'Keine Artikel verfügbar',
      'all': 'Alle',
      'user_page_title': 'Benutzerseite',
      'user_message': 'Du bist ein Benutzer und darfst diese Funktionalität nutzen.',
      'content_card_title': 'Dein Inhaltstitel',
      "form_submission_success": "Formular erfolgreich übermittelt!",
      "error_generic": "Fehler: {error}",
      "select_previous_image": "Bitte wählen Sie zuerst das vorherige Bild aus.",
      "permission_denied": "Zugriff verweigert!",
      "permission_permanently_denied": "Zugriff dauerhaft verweigert. Bitte aktivieren Sie ihn in den Einstellungen.",
      "select_image_source": "Bildquelle auswählen",
      "camera": "Kamera",
      'image_picker_title': 'Bild auswählen',
      "gallery": "Galerie",
      "select_topic": "Thema auswählen",
      "select_topic_error": "Bitte wählen Sie ein Thema aus",
      "first_name": "Vorname",
      "first_name_error": "Bitte geben Sie Ihren Vornamen ein.",
      "last_name": "Nachname",
      "last_name_error": "Bitte geben Sie Ihren Nachnamen ein.",
      "phone": "Telefon",
      "message_hint": "Kurznachricht",
      "message_error": "Bitte eine Nachricht eingeben",
      "terms_agreement": "Mit der Eingabe meiner Daten und der Betätigung des Buttons 'Nachricht senden' erkläre ich mein Einverständnis zur Nutzung der angegebenen Daten zur Beantwortung meiner Kontaktanfrage.",
      "send_message": "Nachricht senden",
      "contact_form": "Kontaktformular",
      "support": "Support",
      "call_phone_number": "Rufen Sie {phoneNumber} an",
      "call": "Anrufen",
      "frequently_asked_questions": "Häufige Fragen",
      "live_chat": "Live Chat",
      "live_chat_hours": "Mo-Fr von 8:00 bis 19:00 Uhr",
      "customer_service": "Kundenservice",
      "customer_service_hours": "Mo-Fr von 8:00 bis 20:00 Uhr\nSa von 8:00 bis 16:00 Uhr"
    },
  };

  String translate(String key, [Map<String, String>? substitutions]) {
    String value = _localizedValues[locale.languageCode]?[key] ?? key;
    if (substitutions != null) {
      substitutions.forEach((key, replacement) {
        value = value.replaceAll('{$key}', replacement);
      });
    }
    return value;
  }
}

class AppLocalizationsDelegate extends LocalizationsDelegate<AppLocalizations> {
  const AppLocalizationsDelegate();

  @override
  bool isSupported(Locale locale) {
    return ['en', 'de'].contains(locale.languageCode);
  }

  @override
  Future<AppLocalizations> load(Locale locale) {
    return SynchronousFuture<AppLocalizations>(AppLocalizations(locale));
  }

  @override
  bool shouldReload(AppLocalizationsDelegate old) => false;
}
